#!/data/data/com.termux/files/usr/bin/python3

import sys, os



# ________________________________

__author__ = 'VistoPreto'
__version__ = '0.02'

# ________________________________


if len(sys.argv) == 1:
	arg = ''
elif len(sys.argv) == 2:
	arg = sys.argv[1]
else:
	arg = 'err'

descricao = '''

TeleX.py [ -about ] [ -start ] [ -uninstall ]

-about		Sobre o script
-start		Inciar funçoes do script
-unistall	Remover instalação do script
-upgrade	Atualiza o script para versão mais atual

'''

def arg_analise(x):
	if x == '-about':
		print()
		print('Desenvolvido por ', __author__)
		print('Version ', __version__)
		print()
	elif x == '-start':
		os.system('python /data/data/com.termux/files/usr/share/telex/main.py')
	elif x == '-uninstall':
		os.system('bash /data/data/com.termux/files/usr/share/telex/uninstall')
	elif x == '-upgrade':
		os.system('bash /data/data/com.termux/files/usr/share/telex/upgrade')
	elif x == '' or x == 'err':
		print(descricao)
	else:
		print(descricao)

arg_analise(arg)
